### ISSUE TITLE
Needing ansible to setup the containers; can this be changed?

### ISSUE THREAD

**Issue by gamefiend** [OlafRadicke/booktype_with_docker#1]
Hi, 

I am going through the setup for this (thanks for working on this, btw!) and see that it uses ansible on the host to run. I'd like to have something that runs just with docker. Are there problems doing this from a Dockerfile that caused this set up to happen?  Would love to help out with this if it is the case.

Thanks,

Quinn

**Comment by OlafRadicke** [comment]
Hi Quinn,

you can use docker compose or OpenShft or all other -  what ever do you like. But the main issue is this: 

https://forum.sourcefabric.org/discussion/17824/deploying-booktype-as-docker-container/p1

and i can't  finding any solution.

**Comment by gamefiend** [comment]
Hi Olaf,

Thanks for the heads up! I am looking at this right now to see if I can find a workaround of some sort.
